table DimCategory
	lineageTag: dimcategory-tag

	column CategoryID
		dataType: int64
		summarizeBy: none
		sourceColumn: CategoryID
		lineageTag: CategoryID-tag

	column CategoryName
		dataType: string
		summarizeBy: none
		sourceColumn: CategoryName
		lineageTag: CategoryName-tag

	partition DimCategory = m
		mode: import
		source =
				let
					Src = Csv.Document(File.Contents(DataFolder & "DimCategory.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Prom = Table.PromoteHeaders(Src, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Prom, {{"CategoryID", Int64.Type}, {"CategoryName", type text}})
				in
					Typed
