table DimProduct
	lineageTag: dimproduct-tag

	column ProductID
		dataType: int64
		summarizeBy: none
		sourceColumn: ProductID
		lineageTag: ProductID-tag

	column ProductName
		dataType: string
		summarizeBy: none
		sourceColumn: ProductName
		lineageTag: ProductName-tag

	column ProductNumber
		dataType: string
		summarizeBy: none
		sourceColumn: ProductNumber
		lineageTag: ProductNumber-tag

	column CategoryID
		dataType: int64
		summarizeBy: none
		sourceColumn: CategoryID
		lineageTag: CategoryID-tag

	column CategoryName
		dataType: string
		summarizeBy: none
		sourceColumn: CategoryName
		lineageTag: CategoryName-tag

	partition DimProduct = m
		mode: import
		source =
				let
					Src = Csv.Document(File.Contents(DataFolder & "DimProduct.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
					Prom = Table.PromoteHeaders(Src, [PromoteAllScalars=true]),
					Typed = Table.TransformColumnTypes(Prom, {{"ProductID", Int64.Type}, {"CategoryID", Int64.Type}, {"ProductName", type text}, {"ProductNumber", type text}, {"CategoryName", type text}})
				in
					Typed
